openapi: 3.0.1
info:
    title: 答案之书
    description: 答案之书是一本神奇的书，能够根据你的问题或者困惑生成对应的解答，为你指点迷津。
    version: "v1"
servers:
    - url: http://127.0.0.1:8082
paths:
    /Get_Answer_of_Number:
        post:
            operationId: GetAnswerofNumber
            summary: 根据给定的数字查询答案之书的内容，并且给出解释
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/InputNums"
            responses:
                "200":
                    description: 答案数据返回
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OutputMessage"
    /Get_Answer_in_Random:
        post:
            operationId: GetAnswerinRandom
            summary: 随机翻开一页书本，对答案之书的内容进行解答
            responses:
                "200":
                    description: 答案数据返回
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OutputMessage"
            x-return-raw:
                description: 标记当前API请求的结果是否经过大模型，当name的值不空时，从插件结果中获取具体字段，类型必须string，直接返回，而不经过大模型。
                mediaType: application/json
                name: message
                type: string
    /Shuffle_Book:
        post:
            operationId: shuffle_book
            summary: 随机刷新或重置答案之书
            responses:
                "200":
                    description: 回执
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/OutputMessage"
            x-return-raw:
                description: 标记当前API请求的结果是否经过大模型，当name的值不空时，从插件结果中获取具体字段，类型必须string，直接返回，而不经过大模型。
                mediaType: application/json
                name: message
                type: string
components:
    schemas:
        InputNums:
            type: object
            required: [number]
            properties:
                number:
                    type: integer
                    description: 获取输入的一个数字
        OutputMessage:
            type: object
            required: [message]
            properties:
                message:
                    type: string
                    description: 回复信息